<?php

namespace App\Models;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Schema;

class DatabaseSqlBackup
{
    /**
     * Create SQL restore dump with schema + data.
     * Splits output into chunk files when chunk size is exceeded.
     *
     * @return array{files: array<int, string>, total_bytes: int, chunk_size_bytes: int}
     */
    public function createRestoreDump(?string $baseName = null, int $chunkSizeBytes = 1048576): array
    {
        $connection = DB::connection();
        $databaseName = $connection->getDatabaseName();
        $pdo = $connection->getPdo();

        if ($baseName === null || trim($baseName) === '') {
            $baseName = 'db_restore_' . now()->format('Y_m_d_His');
        }

        $directory = storage_path('app/backups/sql');
        File::ensureDirectoryExists($directory);

        $chunkIndex = 1;
        $chunkBytes = 0;
        $totalBytes = 0;
        $files = [];
        $handle = null;

        $openNewChunk = function () use (&$chunkIndex, &$chunkBytes, &$files, &$handle, $directory, $baseName): void {
            if (is_resource($handle)) {
                fclose($handle);
            }

            $filePath = $directory . '/' . $baseName . '_part_' . str_pad((string) $chunkIndex, 3, '0', STR_PAD_LEFT) . '.sql';
            $handle = fopen($filePath, 'wb');
            $files[] = $filePath;
            $chunkBytes = 0;
            $chunkIndex++;
        };

        $write = function (string $content) use (&$handle, &$chunkBytes, &$totalBytes, $chunkSizeBytes, $openNewChunk): void {
            if (!is_resource($handle)) {
                $openNewChunk();
            }

            $length = strlen($content);
            if ($chunkBytes > 0 && ($chunkBytes + $length) > $chunkSizeBytes) {
                $openNewChunk();
            }

            fwrite($handle, $content);
            $chunkBytes += $length;
            $totalBytes += $length;
        };

        $write("-- SQL restore dump generated by Neko\n");
        $write('-- Database: `' . $databaseName . "`\n");
        $write('-- Generated at: ' . now()->toDateTimeString() . "\n\n");
        $write("SET FOREIGN_KEY_CHECKS=0;\n");
        $write("SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n\n");

        foreach ($this->getTableNames($databaseName) as $tableName) {
            $createTableData = $connection->select('SHOW CREATE TABLE `' . str_replace('`', '``', $tableName) . '`');
            $createTableSql = array_values((array) $createTableData[0])[1] ?? '';

            $write('-- ----------------------------------------' . "\n");
            $write('-- Table structure for `' . $tableName . '`' . "\n");
            $write('-- ----------------------------------------' . "\n");
            $write('DROP TABLE IF EXISTS `' . $tableName . "`;\n");
            $write($createTableSql . ";\n\n");

            $columns = Schema::getColumnListing($tableName);
            if (empty($columns)) {
                continue;
            }

            $columnSql = '`' . implode('`, `', $columns) . '`';

            $write('-- Data for `' . $tableName . "`\n");
            foreach ($connection->table($tableName)->cursor() as $row) {
                $values = [];
                foreach ($columns as $column) {
                    $values[] = $this->toSqlValue($row->{$column} ?? null, $pdo);
                }

                $write('INSERT INTO `' . $tableName . '` (' . $columnSql . ') VALUES (' . implode(', ', $values) . ");\n");
            }
            $write("\n");
        }

        $write("SET FOREIGN_KEY_CHECKS=1;\n");

        if (is_resource($handle)) {
            fclose($handle);
        }

        return [
            'files' => $files,
            'total_bytes' => $totalBytes,
            'chunk_size_bytes' => $chunkSizeBytes,
        ];
    }

    /**
     * @return array<int, string>
     */
    private function getTableNames(string $databaseName): array
    {
        $rows = DB::select('SHOW FULL TABLES FROM `' . str_replace('`', '``', $databaseName) . '` WHERE Table_type = "BASE TABLE"');

        $tables = [];
        foreach ($rows as $row) {
            $tables[] = (string) array_values((array) $row)[0];
        }

        sort($tables);

        return $tables;
    }

    private function toSqlValue(mixed $value, \PDO $pdo): string
    {
        if ($value === null) {
            return 'NULL';
        }

        if (is_bool($value)) {
            return $value ? '1' : '0';
        }

        if (is_int($value) || is_float($value)) {
            return (string) $value;
        }

        return $pdo->quote((string) $value);
    }
}
